version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"] # Specifies that the device should have GPU capabilities
            driver: nvidia
            count: 1 # Specify the number of GPUs you want to use
    volumes:
      - ollama:/root/.ollama
      - ./Modelfile:/root/.ollama/Modelfile
    restart: always

volumes:
  ollama:
    driver: local

networks:
  default:
    name: poc
    external: true